# Generated by Django 5.0.6 on 2024-05-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historial',
            new_name='Historical',
        ),
    ]
