# Generated by Django 5.0.6 on 2024-05-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase_app', '0002_rename_historial_historical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ticket',
            new_name='ticker',
        ),
    ]
