# Generated by Django 5.0.6 on 2024-05-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase_app', '0003_rename_ticket_product_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historical',
            old_name='ticker_id',
            new_name='product',
        ),
    ]
