# Generated by Django 5.0.6 on 2024-05-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase_app', '0004_rename_ticker_id_historical_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='volume',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
